categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'bug'
  - title: 'Updates'
    labels:
      - 'refactor'
      - 'documentation'
template: |
  ## What’s Changed

  $CHANGES