#!/bin/bash

python test_train_conditional_moments.py
python test_train_conditional_moments_st.py
python test_train_conditional_moments_feat.py
python test_train_wind_conditional_moments.py
python test_out_conditional_moments.py
python test_out_conditional_moments_st.py
python test_out_conditional_moments_feat.py
