# -*- coding: utf-8 -*-
"""Sup3r models with modified content loss functions"""

import tensorflow as tf
from tensorflow.keras.metrics import mean_squared_error
from tensorflow.keras.metrics import kld as kl_divergence

from sup3r.models.base import Sup3rGan
from sup3r.utilities.loss_metrics import max_mean_discrepancy


class Sup3rGanKLD(Sup3rGan):
    """Sup3rGan sub class using mse + kl divergence instead of just
    mse"""

    @staticmethod
    @tf.function
    def calc_loss_gen_content(hi_res_true, hi_res_gen):
        """Calculate the content loss term for the generator model. Use sum
        of mean squared error and kl divergence.

        Parameters
        ----------
        hi_res_true : tf.Tensor
            Ground truth high resolution spatiotemporal data.
        hi_res_gen : tf.Tensor
            Superresolved high resolution spatiotemporal data generated by the
            generative model.

        Returns
        -------
        loss_gen_s : tf.Tensor
            0D tensor generator model loss for the content loss comparing the
            hi res ground truth to the hi res synthetically generated output.
        """

        loss_gen_content = mean_squared_error(hi_res_true, hi_res_gen)
        loss_gen_content += kl_divergence(hi_res_true, hi_res_gen)
        loss_gen_content = tf.reduce_mean(loss_gen_content)

        return loss_gen_content


class Sup3rGanMMD(Sup3rGan):
    """Sup3rGan sub class using mse + max mean discrepancy for content
    loss instead of just mse"""

    @staticmethod
    @tf.function
    def calc_loss_gen_content(hi_res_true, hi_res_gen):
        """Calculate the content loss term for the generator model. Use max
        mean discrepancy + mse instead of just mse.

        Parameters
        ----------
        hi_res_true : tf.Tensor
            Ground truth high resolution spatiotemporal data.
        hi_res_gen : tf.Tensor
            Superresolved high resolution spatiotemporal data generated by the
            generative model.

        Returns
        -------
        loss_gen_s : tf.Tensor
            0D tensor generator model loss for the content loss comparing the
            hi res ground truth to the hi res synthetically generated output.
        """

        loss_gen_content = tf.reduce_mean(mean_squared_error(hi_res_true,
                                                             hi_res_gen))
        loss_gen_content += tf.reduce_mean(max_mean_discrepancy(hi_res_true,
                                                                hi_res_gen))
        return loss_gen_content
