name: Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  make-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: select python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[doc]
      - name: build documentation
        run: |
          cd docs
          make html
      - name: deploy
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
